"""Initial Migration

Revision ID: 7865b27a3792
Revises: 30d2dfdde980
Create Date: 2022-03-14 15:34:35.108149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7865b27a3792'
down_revision = '30d2dfdde980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upvotes')
    op.drop_table('downvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downvotes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('downvote', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], name='downvotes_blog_id_fkey'),
    sa.ForeignKeyConstraint(['name'], ['users.id'], name='downvotes_name_fkey'),
    sa.PrimaryKeyConstraint('id', name='downvotes_pkey')
    )
    op.create_table('upvotes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upvote', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], name='upvotes_blog_id_fkey'),
    sa.ForeignKeyConstraint(['name'], ['users.id'], name='upvotes_name_fkey'),
    sa.PrimaryKeyConstraint('id', name='upvotes_pkey')
    )
    # ### end Alembic commands ###
